### ISSUE TITLE
Peloton tweaks

### ISSUE THREAD

**Issue by ptx2** [ptx2/gymnasticon#19]
Hey @jeremydk I was planning to release 1.1.0 and a new SD card image this weekend. Were you still thinking of opening a PR for the Peloton lag improvements? I can do if you don't have time and are ok with that, full credit to you of course, lmk!

**Comment by jeremydk** [comment]
Now that we've also fixed the cadence issue, I can rebase my pi tomorrow
and test how necessary the lag changes are. If they're required still, I
can get a Pull Request out by tomorrow afternoon for you to ship a 1.1.0 on
Sunday if that's cool with you.
