### ISSUE TITLE
Feature request: Sent data in ANT+

### ISSUE THREAD

**Issue by chriselsen** [ptx2/gymnasticon#33]
I would like to not only connect Zwift to my bike trainer, but also my Garmin Fenix smart watch. Unfortunately Garmin's support for BLE sensors is buggy and currently does not support the Cycling Power Services (CPS) profile.

Therefore it would be great if Gymnasticon could send the same data it has acquired from the bike trainer not only out via BLE to Zwift, but also via ANT+ to the Garmin Watch. 

This project at https://github.com/olympum/ant-cycling-power provides an example for sending cycling power and cadence data out via ANT+ and could serve as an example to be merged here.

**Comment by ptx2** [comment]
Thanks for the suggestion and the link! I've opened a PR here https://github.com/ptx2/gymnasticon/pull/36 that works with the ANT+ stick I have (Anself 0fcf:1008) and with my Wahoo Element Bolt as the receiver.

I plan to do a release in the next few days with this change and some others.
