### ISSUE TITLE
Will this work on Keiser M3? Just need some pointer if possible?

### ISSUE THREAD

**Issue by nealjane** [ptx2/gymnasticon#42]
I have a keiser M3 I- which has Bluetooth.

have previously setup ‘keiser2zwift at GitHub- but the app is incomplete with little help from the original developer for additional services for other cycling apps - peloton, RGT cycling etc.

Ive read this project with interest and I note the “ Support for other bikes can be added easily.” in the project description- ive read through the instructions on setting up with other bikes (numerous times!) - but for the life of me, apart from finding the relevant files and reading through them-  I’m not sure what I’m supposed to alter?!

- I’m totally flumoxed to what needs adding to the files - eg ‘M3’ as the bluetooth title??

Any help available from anyone would be very grateful received!

At its most basic- if i state ‘M3’ in ble-scan as device name and use flywheel as bike settings as starting point? 

Image attached showing Bluetooth details I get from the bike usingnRF connect..
![7FD76BD1-B0E1-4E19-A387-7D6EF4E29426](https://user-images.githubusercontent.com/68538658/107284812-355dbf00-6a56-11eb-8623-8f66435b15be.jpeg)

**Comment by chriselsen** [comment]
Here is a [BLE Simulator for the Keiser M3i](https://github.com/KeiserCorp/Keiser.M3i.BLE-HCI-Simulator), which includes documentation of the packet format. That should help with the development of a custom bike type.

**Comment by nealjane** [comment]
Thanks @chriselsen - that all looks beyond me. 
Will keep an eye out and see if someone else comes along and knows how to do the technical work..!

**Comment by chriselsen** [comment]
@nealjane Just created #50 for experimental Keiser M3 support. Give it a try and let me know how it went.

**Comment by ptx2** [comment]
This has been released in 1.4.0.
