### ISSUE TITLE
Code cleanup: Breakout drop-out filter into util function

### ISSUE THREAD

**Issue by chriselsen** [ptx2/gymnasticon#56]
Currently the bike driver for _flywheel_ uses a drop-out filter for sudden power-drops to 0W. The bike driver for _keiser_ uses a similar drop-out filter, covering both power and cadence drop. 

These filters could be moved into /util/ as a shared utility function. There should not be an issue with the flywheel bike also using the cadence drop filter part.

**Comment by ptx2** [comment]
This is a good opportunity to wrap some tests around it too :-)
