### ISSUE TITLE
Bug Fix: Adapt Keiser driver to different bike versions

### ISSUE THREAD

**Issue by chriselsen** [ptx2/gymnasticon#60]
Keiser M3 bikes come in [multiple revisions](https://dev.keiser.com/mseries/direct/#revision-history) with version 6.29 and lower bikes emitting data packets every ~ 2 seconds and version 6.30 and higher bikes emitting data packets every ~ 0.3 seconds. 
The Keiser stats timer needs to be adapted to these two version of bikes with the timeout value being:
- Version <= 6.29: Timeout: 7 sec
- Version >= 6.30: Timeout: 2 sec (possibly 1 sec)

**Comment by chriselsen** [comment]
Created pull request #63 to address this.

**Comment by ptx2** [comment]
Fixed by #63.
