### ISSUE TITLE
Available metrics for garmin Edge

### ISSUE THREAD

**Issue by byndcivilization** [ptx2/gymnasticon#86]
I have a Garmin Edge 320 that I'm using to record things. With a little trial and error, I've gotten gymasticon to register the pi as an ant+ power sensor and during rides,  the Edge reports back power and cadence. Is there a trick to getting speed out as well or does that not work here.

**Comment by byndcivilization** [comment]
I should mention that im using a peloton bike. I don't see speed metrics being picked up there. So im guessing its not implemented for the peloton.

**Comment by nealjane** [comment]
Hi, yes- speed isn't implemented for any bike. 
If you had to choose between speed vs power - you're better off with power, 

Dev have mentioned previously that apps like zwift will calculate your speed and distance if you want those stats - sync them to Strava and then sync that to Garmin connect perhaps??

**Comment by byndcivilization** [comment]
Rad, I mostly I wanted to make sure I had everything working as expected.

**Comment by adanemayer** [comment]
@byndcivilization Can you share the details of how you got the Edge to pair with the ANT+ USB dongle? I've tried now with both a cheap one and one from Garmin. I have a Garmin Edge 25 I am trying to pair and it doesn't see any available devices with either dongle plugged into the Raspberry Pi that is linked via Bluetooth to my Schwinn IC4. 
I confirmed the Raspberry Pi + IC4 work by pairing my laptop to the Bluetooth signal from Gymnasticon and watching the data stream through so I think it is just a matter of getting the ANT+ registered.

**Comment by nealjane** [comment]
@adanemayer . You Garmin edge 25 doesn’t do power profile. It will do cadence and speed so you need to use Chris elsens update to Gymnasticon - https://github.com/ptx2/gymnasticon/pull/89

this update adds speed and cadence profile over ant+ which your Garmin will be able to connect to.
